### ISSUE TITLE
when doing the command it keeps saying : example server status The server was unable to be pinged or you mis-typed the info

### ISSUE THREAD

**Issue by normaluser12354** [Baggette/minecraft-server-ping-example#1]
when running the command !mcstatus it just says the server was unable to be pinged

**Comment by normaluser12354** [comment]
PS C:\Users\jason\Documents\discord minecraft bot test> node .
bot started
AssertionError [ERR_ASSERTION]: Expected 'options' to be an object or undefined, got number
    at C:\Users\jason\Documents\discord minecraft bot test\node_modules\minecraft-server-util\dist\status.js:46:25
    at Generator.next (<anonymous>)
    at C:\Users\jason\Documents\discord minecraft bot test\node_modules\minecraft-server-util\dist\status.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\jason\Documents\discord minecraft bot test\node_modules\minecraft-server-util\dist\status.js:4:12)
    at status (C:\Users\jason\Documents\discord minecraft bot test\node_modules\minecraft-server-util\dist\status.js:40:12)
    at Object.<anonymous> (C:\Users\jason\Documents\discord minecraft bot test\node_modules\minecraft-server-util\dist\status.js:113:17)
    at Generator.next (<anonymous>)
    at C:\Users\jason\Documents\discord minecraft bot test\node_modules\minecraft-server-util\dist\status.js:8:71
    at new Promise (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
  
  here is the log

**Comment by Baggette** [comment]
that is strange. I will look into it tomorrow after school.

**Comment by normaluser12354** [comment]
It was because I didnt have the latest minecraft server util installed

**Comment by Baggette** [comment]
Ahhh okay. good luck with the bot

**Comment by Baggette** [comment]
I will close is unless you require more help.
